// users
export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE'

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const EDIT_NAME_REQUEST = 'EDIT_NAME_REQUEST'
export const EDIT_NAME_SUCCESS = 'EDIT_NAME_SUCCESS'
export const EDIT_NAME_FAILURE = 'EDIT_NAME_FAILURE'

// test
export const GET_TESTS_REQUEST = 'GET_TESTS_REQUEST'
export const GET_TESTS_SUCCESS = 'GET_TESTS_SUCCESS'
export const GET_TESTS_FAILURE = 'GET_TESTS_FAILURE'

export const GET_TEST_REQUEST = 'GET_TEST_REQUEST'
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS'
export const GET_TEST_FAILURE = 'GET_TEST_FAILURE'

export const ADD_TEST_REQUEST = 'ADD_TEST_REQUEST'
export const ADD_TEST_SUCCESS = 'ADD_TEST_SUCCESS'
export const ADD_TEST_FAILURE = 'ADD_TEST_FAILURE'

export const EDIT_TEST_REQUEST = 'EDIT_TEST_REQUEST'
export const EDIT_TEST_SUCCESS = 'EDIT_TEST_SUCCESS'
export const EDIT_TEST_FAILURE = 'EDIT_TEST_FAILURE'
